name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: run headless test
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: npm test
      - run: find . > files.txt
      - uses: actions/upload-artifact@v2
        with:
          name: files.txt
          path: files.txt
      # - name: Fix paths # https://stackoverflow.com/questions/45602358/lcov-info-has-absolute-path-for-sf
      #   run: sed -i -- 's/..\\..\\//g' coverage/lcov.info
      - name: Validate codecov.yml
        if: matrix.os == 'ubuntu-latest'
        run: curl --data-binary @.github/codecov.yml https://codecov.io/validate
      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json || echo 'Codecov upload failed'
