name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: run headless test
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: npm test
      - name: Validate codecov.yml
        run: curl --data-binary @.github/codecov.yml https://codecov.io/validate
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json || echo 'Codecov upload failed'
